---
- name: Configure EC2 instance
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create index.html file
      template:
        src: templates/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted
